### ISSUE TITLE
Issues installing with v1.4.0

### ISSUE THREAD

**Issue by hewrin** [SaraVieira/react-social-sharing#17]
I get this error when I use the latest version `1.4.0`

below is my error

```
error /Users/farisroslan/Desktop/projects/postco-apps/postco/client/node_modules/react-social-sharing: Command failed.
Exit code: 1
Command: npm run dist:modules
Arguments:
Directory: /Users/farisroslan/Desktop/projects/postco-apps/postco/client/node_modules/react-social-sharing
Output:
> react-social-sharing@1.4.0 dist:modules /Users/farisroslan/Desktop/projects/postco-apps/postco/client/node_modules/react-social-sharing
> del-cli ./dist-modules && cross-env BABEL_ENV=modules babel ./src --out-dir ./dist-modules

sh: del-cli: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-social-sharing@1.4.0 dist:modules: `del-cli ./dist-modules && cross-env BABEL_ENV=modules babel ./src --out-dir ./dist-modules`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react-social-sharing@1.4.0 dist:modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/farisroslan/.npm/_logs/2018-08-14T06_16_36_346Z-debug.log
```
`v1.3.3` and `1.3.2` work fine

Thanks for the library!

**Comment by SaraVieira** [comment]
I will fix this today and also most likely clean up all the way these modules are created and just use something like webpack for this :)

**Comment by hewrin** [comment]
Bless you, friend 😃

**Comment by uturnr** [comment]
I'm having similar issues when installing 1.4.1 with yarn:

```
error /Users/codycody/uturnr/specials/node_modules/react-social-sharing: Command failed.
Exit code: 1
Command: npm run dist:modules
Arguments:
Directory: /Users/codycody/uturnr/specials/node_modules/react-social-sharing
Output:
> react-social-sharing@1.4.1 dist:modules /Users/codycody/uturnr/specials/node_modules/react-social-sharing
> cross-env BABEL_ENV=modules babel ./src --out-dir ./dist-modules

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn babel ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-social-sharing@1.4.1 dist:modules: `cross-env BABEL_ENV=modules babel ./src --out-dir ./dist-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-social-sharing@1.4.1 dist:modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/codycody/.npm/_logs/2018-09-09T23_03_13_338Z-debug.log
```
